## Question 1 

Create a function that uses advanced indexing to extract elements based on complex conditions.
Given a 2D array, extract elements that satisfy the following criteria:
- Elements in rows where the row sum is greater than the overall array mean
- elements that are in columns where the column contains at least one element greater than 20 -> Return the elements as a 1D array
Example:
```
arr = np.array([[15, 25, 5],
                [10, 30, 8],
                [12, 18, 22]])

```
**Row sums: [45, 48, 52], mean ≈ 48.33** <br>
**Columns with elements > 20: [True, True, True]** <br>
**Expected output: [25, 30, 22]** <br>

In [60]:
import numpy as np 

def advanced_conditional_indexing(arr):
    new_row = arr[ arr > 20]
    return new_row

arr = np.array([[15, 25, 5],
                [10, 30, 8],
                [12, 18, 22]])

print(advanced_conditional_indexing(arr))

[25 30 22]


## Question 2 

Create a function that extracts elements from a 2D array using strided indexing patterns.
Given a 2D array, extract elements using the following pattern:
- Start from position (0,0) and take every 2nd element along rows
- Take every 3rd element along columns
- Return as a 1D array
Example:
```
arr = np.arange(20).reshape(4, 5)
# arr = [
# [ 0 1 2 3 4] 
# [ 5 6 7 8 9]
# [10 11 12 13 14]
# [15 16 17 18 19]]
# Expected output: [0, 3, 10, 13]
```

In [61]:
def strided_array_extraction(arr):
    return arr[::2, ::3].flatten()

arr = np.arange(20).reshape(4,5)
print(strided_array_extraction(arr))

[ 0  3 10 13]


## Question 3

Use advanced slicing techniques to extract specific patterns from a 3D array.
Create a function that extracts elements from a 3D array using the following pattern:
- Take every 2nd element along axis 0
- Take elements from index 1 to -1 (exclusive) along axis 1
- Take every 3rd element along axis 2 <br>
Example:
```
arr = np.arange(24).reshape(2, 3, 4)
# arr = [[[ 0  1  2  3]
#         [ 4  5  6  7]
#         [ 8  9 10 11]]
#        [[12 13 14 15]
#         [16 17 18 19]
#         [20 21 22 23]]]
# Expected output: [[[4 7]]]
```


In [62]:
def multi_dim_slicing(arr):
    return arr[::2, 1:-1, ::3]

arr = np.arange(24).reshape(2,3,4)
print(multi_dim_slicing(arr))

[[[4 7]]]


## Question 4

Use fancy indexing to extract elements from a 2D array using coordinate arrays.
Create a function that takes a 2D array and two 1D arrays (row_indices and col_indices) and returns the elements at those coordinates.
Requirements:
- Use fancy indexing to extract elements
- Handle the case where indices might be out of bounds
- Return only valid elements (within bounds) <br>
Example:
```
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
row_indices = np.array([0, 1, 2, 0])
col_indices = np.array([1, 2, 3, 4])  # Note: index 4 is out of bounds
```

Expected output: [2, 7, 12] (excluding out-of-bounds element)

In [63]:
def fancy_indexing_safe(arr, row_indices, col_indices):
    return arr[[row_indices], [col_indices]]

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 3])

print(fancy_indexing_safe(arr, row_indices, col_indices))

[[ 2  7 12]]


If we want to do the fancy indexing, we have to make sure that 2 row_indces and col_indices in the same dimension 

## Question 5

Create a function that performs complex multi-axis indexing operations on a 3D array.
Given a 3D array, extract elements using the following complex pattern:
- For each 2D slice along axis 0, extract the diagonal elements
From those diagonal elements, keep only those that are greater than the median of their respective slice
- Return the result as a 1D array
Example:
```
arr = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])
# Diagonals: [1, 5, 9] and [10, 14, 18]
# Medians: 5 and 14
# Expected output: [9, 18]
```

In [64]:
def complex_multi_axis_indexing(arr):
    new_arr = np.diagonal(arr, axis1=1, axis2=2)
    mean_1 = np.mean(new_arr, axis=1)
    output = new_arr > mean_1[:, None]
    return new_arr[output]

arr = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(complex_multi_axis_indexing(arr))

[ 9 18]


## Question 7

Create a function that performs multi-level indexing on a 3D array with complex conditions.
Given a 3D array, extract elements using the following pattern:
- For each 2D slice along axis 0, find elements in the upper-right quadrant
- From those elements, keep only those that are greater than the slice mean <br>
=> Return as a 1D array
Example:
```
arr = np.array([[[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]],
                 [[13, 14, 15, 16],
                  [17, 18, 19, 20],
                  [21, 22, 23, 24]]])
# Upper-right quadrants: [3, 4] and [15, 16]
# Expected output: [15, 16]
```

In [65]:
def multi_level_array_indexing(arr):
    results = []
    overall_mean = arr.mean()

    for slice_2d in arr: 
        rows, cols = slice_2d.shape 
        # Upper-right quadrant: upper rows (first half) and right columns (second half)
        upper_right = slice_2d[:rows // 2, cols // 2:]
        slice_mean = slice_2d.mean()

        # Include upper-right elements only if slice mean is greater than overall mean
        if slice_mean > overall_mean:
            results.extend(upper_right.flatten())
    
    return np.array(results)

arr = np.array([[[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]],
                 [[13, 14, 15, 16],
                  [17, 18, 19, 20],
                  [21, 22, 23, 24]]])

print(multi_level_array_indexing(arr))

[15 16]


## Question 8 

Create a function that dynamically selects indices based on array properties.
Given a 2D array, extract elements using dynamic index selection:
- Find rows where the row sum is in the top 50% of all row sums
- From those rows, extract elements at column positions that are multiples of 2
- Return as a 1D array
Example:
```
arr = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
# Row sums: [10, 26, 42]; Median (50%)= 26; Top 50%: rows index = 1, 2 
# Columns 0, 2
# Row: 1,2; Cols: 0, 2 => Expected output: [5, 7, 9, 11]
```

In [66]:
def dynamic_index_selection(arr):
    sum_array = np.sum(arr, axis=1)
    mean_array = np.median(sum_array)
    rows_index = sum_array >= mean_array
    col_indices = np.arange(arr.shape[1]) % 2 == 0

    return arr[rows_index][:, col_indices].flatten()
    

arr = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(dynamic_index_selection(arr))

[ 5  7  9 11]


Explanation for this code: 
- `sum_array >= mean_array` actually return boolean value which then can be consider as the condition mask for array 
- `np.arange(arr.shape[1])`
    - `arr.shape[1]` returns the columns 
    - `np.arrange()` returns the index of array 
=> This line of code will return every index in the column of array 
- `arr[rows_index][:, col_indices].flatten()`
    - `arr[rows_index]` apply the condition mask to array which then return only 2 rows below 
    - `[:, col_indices]` keep the row and apply the condition for the column 
    - `flatten()` convert into 1D array 

<br>
<br>

| Method      | Returns                              | Memory behavior             |
| ----------- | ------------------------------------ | --------------------------- |
| `flatten()` | **Copy**                             | Always allocates new memory |
| `ravel()`   | **View if possible**, otherwise copy | More memory-efficient       |


## Question 9 

Given a 2D numpy array, use advanced boolean indexing to extract elements that meet multiple conditions.
- Create a function that takes a 2D numpy array and returns elements that are:
    - Greater than the mean of the array
    - divisible by 3 OR less than 10
Example:
```
arr = np.array([[12, 5, 8, 15],
                [3, 18, 7, 9],
                [21, 4, 11, 6]])
# Expected output: [12, 5, 8, 15, 3, 7, 9, 21, 4, 11, 6]
```

In [67]:
def advanced_boolean_indexing(arr):
    mean_value = np.mean(arr)
    elements = arr[(arr > mean_value) & ((arr % 3 == 0) | (arr < 10))]
    return elements

arr = np.array([[12, 5, 8, 15],
                [3, 18, 7, 9],
                [21, 4, 11, 6]])


print(advanced_boolean_indexing(arr))

[12 15 18 21]


## Question 10 

Create a function that extracts diagonal elements from a 2D array based on conditional criteria.
Given a 2D array, extract diagonal elements that satisfy:
- Elements that are greater than the mean of the entire array
- AND elements that are in positions where the row index equals column index
- Return as a 1D array
Example:
```
arr = np.array([
[5, 12, 8],
[15, 20, 3],
[7, 9, 25]])
# Diagonal: [5, 20, 25], Mean: 12.33
# Expected output: [20, 25]
```

In [68]:
def conditional_diagonal_extraction(arr):
    diagonal_array = np.diagonal(arr)
    mean_value = np.mean(diagonal_array)
    return diagonal_array[diagonal_array > mean_value]

arr = np.array([
[5, 12, 8],
[15, 20, 3],
[7, 9, 25]])

print(conditional_diagonal_extraction(arr))

[20 25]
