## Question 1 

Create a function that uses advanced indexing to extract elements based on complex conditions.
Given a 2D array, extract elements that satisfy the following criteria:
Elements in rows where the row sum is greater than the overall array mean
AND elements that are in columns where the column contains at least one element greater than 20
Return the elements as a 1D array
Example:
arr = np.array([[15, 25, 5],
                [10, 30, 8],
                [12, 18, 22]])
# Row sums: [45, 48, 52], mean ≈ 48.33
# Columns with elements > 20: [True, True, True]
# Expected output: [25, 30, 22]

In [ ]:
def advanced_conditional_indexing(arr):
    # Your code here
    pass

## Question 2 

Create a function that extracts elements from a 2D array using strided indexing patterns.
Given a 2D array, extract elements using the following pattern:
- Start from position (0,0) and take every 2nd element along rows
- Take every 3rd element along columns
- Return as a 1D array
Example:
arr = np.arange(20).reshape(4, 5)
# arr = [
# [ 0 1 2 3 4] 
# [ 5 6 7 8 9]
# [10 11 12 13 14]
# [15 16 17 18 19]]
# Expected output: [0, 3, 10, 13]

In [ ]:
def strided_array_extraction(arr):
    # Your code here
    pass

## Question 3

Use advanced slicing techniques to extract specific patterns from a 3D array.
Create a function that extracts elements from a 3D array using the following pattern:
Take every 2nd element along axis 0
Take elements from index 1 to -1 (exclusive) along axis 1
Take every 3rd element along axis 2
Example:

arr = np.arange(24).reshape(2, 3, 4)
# arr = [[[ 0  1  2  3]
#         [ 4  5  6  7]
#         [ 8  9 10 11]]
#        [[12 13 14 15]
#         [16 17 18 19]
#         [20 21 22 23]]]
# Expected output: [[[5 8]]]



In [ ]:
def multi_dim_slicing(arr):
    # Your code here
    pass

## Question 4

Use fancy indexing to extract elements from a 2D array using coordinate arrays.
Create a function that takes a 2D array and two 1D arrays (row_indices and col_indices) and returns the elements at those coordinates.
Requirements:
Use fancy indexing to extract elements
Handle the case where indices might be out of bounds
Return only valid elements (within bounds)
Example:
 
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
row_indices = np.array([0, 1, 2, 0])
col_indices = np.array([1, 2, 3, 4])  # Note: index 4 is out of bounds

Expected output: [2, 7, 12] (excluding out-of-bounds element)

In [ ]:
def fancy_indexing_safe(arr, row_indices, col_indices):
    # Your code here
    pass

## Question 5

Create a function that performs complex multi-axis indexing operations on a 3D array.
Given a 3D array, extract elements using the following complex pattern:
For each 2D slice along axis 0, extract the diagonal elements
From those diagonal elements, keep only those that are greater than the median of their respective slice
Return the result as a 1D array
Example:
arr = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])
# Diagonals: [1, 5, 9] and [10, 14, 18]
# Medians: 5 and 14
# Expected output: [9, 18]

In [ ]:
def complex_multi_axis_indexing(arr):
    # Your code here
    pass

## Question 6 



## Question 7

Create a function that performs multi-level indexing on a 3D array with complex conditions.
Given a 3D array, extract elements using the following pattern:
For each 2D slice along axis 0, find elements in the upper-right quadrant
From those elements, keep only those that are greater than the slice mean
Return as a 1D array
Example:
arr = np.array([[[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]],
                 [[13, 14, 15, 16],
                  [17, 18, 19, 20],
                  [21, 22, 23, 24]]])
# Upper-right quadrants: [3, 4] and [15, 16]
# Expected output: [15, 16]

In [ ]:
def multi_level_array_indexing(arr):
    # Your code here
    pass

## Question 8 

Create a function that dynamically selects indices based on array properties.
Given a 2D array, extract elements using dynamic index selection:
- Find rows where the row sum is in the top 50% of all row sums
- From those rows, extract elements at column positions that are multiples of 2
- Return as a 1D array
Example:
arr = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
# Row sums: [10, 26, 42]; Median (50%)= 26; Top 50%: rows index = 1, 2 
# Columns 0, 2
# Row: 1,2; Cols: 0, 2 => Expected output: [5, 7, 9, 11]

In [ ]:
def dynamic_index_selection(arr):
    # Your code here
    pass

## Question 9 

Given a 2D numpy array, use advanced boolean indexing to extract elements that meet multiple conditions.
Create a function that takes a 2D numpy array and returns elements that are:
Greater than the mean of the array
AND divisible by 3
OR less than 10
Example:
arr = np.array([[12, 5, 8, 15],
                [3, 18, 7, 9],
                [21, 4, 11, 6]])
# Expected output: [12, 5, 8, 15, 3, 7, 9, 21, 4, 11, 6]

In [ ]:
def advanced_boolean_indexing(arr):
    # Your code here
    pass

## Question 10 

Create a function that extracts diagonal elements from a 2D array based on conditional criteria.
Given a 2D array, extract diagonal elements that satisfy:
- Elements that are greater than the mean of the entire array
- AND elements that are in positions where the row index equals column index
- Return as a 1D array
Example:
arr = np.array([
[5, 12, 8],
[15, 20, 3],
[7, 9, 25]])
# Diagonal: [5, 20, 25], Mean: 12.33
# Expected output: [20, 25]

In [ ]:
def conditional_diagonal_extraction(arr):
    # Your code here
    pass