# Numpy 

## Definition 

NumPy (Numerical Python) is the foundational library for numerical computing in Python. It provides: 
- **ndarray** - a fast, memory-efficient multidimensional array 
- **Vectorized operation** - operations applied on whole arrays without loops 
- **Broadcasting** - automatic expansion of shapes to match operations 
- etc 

## Core concept: The ndarray

A NumPy array is similar to a Python list, but much faster and supports many operations that lists cannot do 

For example,

In [97]:
import numpy as np 

arr_initial = np.array([1,2,3,4,5])
print(arr_initial)
print(type(arr_initial))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Creating Arrays

We can create arrays in many ways

1. From Python list 

In [98]:
a = np.array([1,2,3])

print(a)

[1 2 3]


2. 2D array

In [99]:
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


3. Arrays filled with zeros or ones

In [100]:
zero_matrix = np.zeros((3,4)) # A matrix with 4 columns * 3 rows 
one_matrix = np.ones((2,2)) # A matrix with 2 columns * 2 rows 
fulfill_matrix = np.full((3,3), 7)

print("Zero matrix: ")
print(zero_matrix)
print("="*20)

print("One matrix: ")
print(one_matrix)
print("="*20)

print("Full value matrix: ")
print(fulfill_matrix)
print("="*20)

Zero matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One matrix: 
[[1. 1.]
 [1. 1.]]
Full value matrix: 
[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Arrays filled with constants

In [101]:
even_array = np.arange(0,10,2) # an array from 0 to 10 with step 2
another_array = np.linspace(0, 1, 5) # An array have 5 elements from 0 to 1

print(even_array)
print(another_array)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


5. Random arrays

In [102]:
print(np.random.randint(0, 10, size=(3,3)), "\n")
print(np.random.randn(3,2), "\n")
print(np.random.random(5))

[[8 5 7]
 [6 9 9]
 [0 7 2]] 

[[ 1.32338267  1.12125507]
 [-1.32117531  2.3734017 ]
 [-0.84719475 -0.85333808]] 

[0.79477947 0.6045344  0.31728568 0.53762792 0.25655423]


6. Reshaping arrays

In [103]:
arr = np.arange(12)
arr.reshape(3, 4)          # new shape (3×4)
arr.reshape(-1, 2)         # auto compute dimension


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### Array attributes 


In [104]:
arr = np.array([[1,2,3], [4,5,6]])

print("Current array:")
print(arr)
print("="*20)

print("The Shape of an array")
print(arr.shape) # Return the dimension of a matrix which is 2*3
print("="*20)

Current array:
[[1 2 3]
 [4 5 6]]
The Shape of an array
(2, 3)


An attribute that might cause quite a lot of confuse which is `arr.ndim`. This attribute will return our matrix's dimension or we can understand that it counts the number of axies. So basically, the axis will base on the shape of a matrix 
- (a,) -> 1 axis 
- (a,b) -> 2 axis 
- (a,b,c) -> 3 axis 
- (a,b,c,d) -> 4 axis 

So above matrix, it returns **(2,3)** which define 2 axis or the result of `ndim` is 2 

In [105]:
print(arr.ndim)

2


Another attributes 

In [106]:
print(arr.dtype) # Return data type of an array
print(arr.size) # Return the total elements inside that matrix 
print(arr.itemsize) # Return bytes per element

int64
6
8


### Indexing & Slicing

NumPy indexing is richer than Python lists and allows multidimensional selection

#### Basic indexing

For a 2D array, indexing uses: 

```
arr[row_selection, column_selection]
```

A colon `:` means -> take everything along that axis 
- : -> take all rows or all columns 
- 0:2 -> take indices 0 and 1 
- ::2 -> take every 2 steps

In [107]:
print(f"First row: {arr[0]}")
print(f"Element at row 1 and column 2 is: {arr[1,2]}") 

First row: [1 2 3]
Element at row 1 and column 2 is: 6


#### Slicing

In [108]:
print("Return the row that correspond with column 1: ", arr[:, 1])
print("Return first 2 rows: ", arr[0:2, :])
print("Every second column: ",arr[:, ::2])

Return the row that correspond with column 1:  [2 5]
Return first 2 rows:  [[1 2 3]
 [4 5 6]]
Every second column:  [[1 3]
 [4 6]]


#### Boolean indexing 

Allows filtering by condition 

In [109]:
boolean_matrix = np.array([[1,4,6], [5,7,9]])

mask = boolean_matrix > 3 # Check which element is larger than 3 
boolean_matrix[mask]

array([4, 6, 5, 7, 9])

#### Fancy indexing

Fancy indexing use integer arrays / lists rather than conditions 

For example, 

In [110]:
another_arr = np.array([10,20,30,40,50])
another_arr[[0,2,4]]

array([10, 30, 50])

In [111]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

A[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

### Broadcasting & Expand Dims

Allows arithmetic operations on arrays of different shapes without explicit loops 

#### Broadcasting Rules 

2 arrays can broadcast together if 
- Their dimensions are equal
- One of them is 1 
- Or one of them is missing (implicitly 1)

In [112]:
arr = np.array([[1,2,3],[4,5,6]])
arr + 10


array([[11, 12, 13],
       [14, 15, 16]])

#### Broadcasting with vectors

In [113]:
A = np.array([[1,2,3],
              [4,5,6]])
b = np.array([1,1,1])

A + b


array([[2, 3, 4],
       [5, 6, 7]])

#### expand_dims

In [114]:
A = np.array([1,2,3])
B = np.array([4,5,6])

A[:, None]   # shape becomes (3,1)
B[None, :]   # shape becomes (1,3)


array([[4, 5, 6]])