## NumPy - Mathematical & Statistical Operations


### Elementwise operations

A mathematical operations applied independently to each element of one or more arrays. NumPy performs these operations in **vectorized** form 

For example,


In [14]:
import numpy as np 

a = np.array([1,2,3])
b = np.array([4,5,6])

result = a + b 
print(result)
print(type(result))

[5 7 9]
<class 'numpy.ndarray'>


Where we defined 2 arrays and add them with corresponding row and column number. There are still more elementwise operations, which are

In [15]:
numpy_add = np.add(a,b)

print(numpy_add)
print(type(numpy_add))

[5 7 9]
<class 'numpy.ndarray'>


In [16]:
multi_result = np.multiply(a, b)
print(multi_result)

[ 4 10 18]


In [17]:
power_result = np.power(a, b)
print(power_result)

[  1  32 729]


In [18]:
sqrt_result = np.sqrt(a)
print(sqrt_result)

[1.         1.41421356 1.73205081]


In [19]:
log_result = np.log(a)
print(log_result)

[0.         0.69314718 1.09861229]


In [20]:
exp_result = np.exp(a)
print(exp_result)

[ 2.71828183  7.3890561  20.08553692]


### Reduction Operation (Aggregation)

Reduction operation collapse an array into a single value or fewer values, usually by summing, averaging, or finding min/max. NumPy implements these as highly optimized routines

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.sum())
print(arr.mean())
print(arr.std()) # Calculate the standard deviation
print(arr.var())
print(arr.min())
print(arr.max())

15
3.0
1.4142135623730951
2.0
1
5


### Axis-based operations 

Axis-based operations perform reductions **along a specific dimension** of an array.

In [ ]:
A = np.array([[1,2,3], [4,5,6]])

print(A.sum(axis=0)) # sum by row
print(A.sum(axis=1)) # sum by column 

[5 7 9]
[ 6 15]


#### Different kind of implementation

We can use function API or method API 

In [25]:
np.sum(A, axis=0)

#or 

A.sum(axis=0)

array([5, 7, 9])

### Sorting & Ranking

Sorting arranges array elements in ascending order. Whereas, ranking returns the indices that would sort the array

In [ ]:
arr = np.array([30,10,20])

print(np.sort(arr))
print(np.argsort(arr)) # return the original index of each value before sorting

[10 20 30]
[1 2 0]


#### Different sorting methods 

1. `np.sort` (return sorted copy)

In [ ]:
new_array = np.sort(arr)
print(new_array)

[10 20 30]


2. `arr.sort()` (sorts in place)

In [ ]:
arr.sort()
print(arr)

[10 20 30]


### Statistical functions 

Statistical functions summarize distribution characteristics of data: mean, median, quantile, percentile, correlation,...

In [31]:
arr = np.array([1,2,3,4,5])
print(np.median(arr))
print(np.percentile(arr, 75))

3.0
4.0


So the `percentile` here is a bit tricky to calculate it, it is following within this formula 

```
(P/100) * (N - 1)
```

where 
- P is the number of percentile that define in the code, in this case, it is 75 
- N is the number of element in an array 

So in above example, we have 

(75/100) * (5-1) = 4 

#### Different statistical methods 


In [33]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.quantile(arr, 0.25))
print(np.corrcoef(arr1, arr2))
print(np.cov(arr1, arr2))

2.0
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


So the formula to calculate the quantile is kind of the same with percentage 

```
position = q * (N - 1)
```

Where **q** is the value specific in the code 

And the covariance and correlation coefficient is the mathematical formula 

### Linear Algebra

NumPy's `linalg` module implements matrix operations used in ML, optimization, and scientific computation.

In [38]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A @ B)  # matrix multiplication
print(A.T) # Transpose
print(np.linalg.inv(A)) # Inverse
print(np.linalg.det(A)) # Determinant 
print(np.linalg.eig(A))


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
